services:
  postgres:
    image: postgres:16
    container_name: cas_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cas
      POSTGRES_PASSWORD: caspassword
      POSTGRES_DB: casdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: